window.SAMPLE_CATALOGUE_DATA = {
  "updatedAt": "2026-05-25T07:56:11.954006",
  "rows": [
    {
      "Record ID": "CAT-001",
      "Approval Status": "Approved",
      "Property Name": "The Town House Hilton The Pearl",
      "Category": "Villa",
      "Area": "The Pearl",
      "Address": "Tower AQ-07, Pearl Boulevard in the Abraj Quartier at The Pearl-Qatar, Doha",
      "Unit Type": "2 Bedroom Duplex Villa",
      "Bedrooms": 2,
      "Size SQM": "163-167",
      "Monthly Rate QAR": 20000,
      "Monthly Rate USD Approx": 5479.45,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "With gym access, Beach access, discount on F&B and Spa",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": null,
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.thetownhouses.qa/",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://the-townhouses-the-pearl-qatar.dohacityhotels.com/data/Photos/OriginalPhoto/13452/1345282/1345282553.JPEG",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": "https://georgetown.box.com/s/0g9m2wok2bwwya1yhe34swnw9bhe1h8f",
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-002",
      "Approval Status": "Approved",
      "Property Name": "The Town House Hilton The Pearl",
      "Category": "Villa",
      "Area": "The Pearl",
      "Address": "Tower AQ-07, Pearl Boulevard in the Abraj Quartier at The Pearl-Qatar, Doha",
      "Unit Type": "2 Bedroom Villa with Pool",
      "Bedrooms": 2,
      "Size SQM": "145-146",
      "Monthly Rate QAR": 26000,
      "Monthly Rate USD Approx": 7123.29,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "With gym access, Beach access, discount on F&B and Spa",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Yassine",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.thetownhouses.qa/",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": "https://georgetown.box.com/s/0802ftziyjkfjtllylep5ox5a0ekmvyf",
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-003",
      "Approval Status": "Approved",
      "Property Name": "The Town House Hilton The Pearl",
      "Category": "Villa",
      "Area": "The Pearl",
      "Address": "Tower AQ-07, Pearl Boulevard in the Abraj Quartier at The Pearl-Qatar, Doha",
      "Unit Type": "3 Bedroom Duplex Villa",
      "Bedrooms": 3,
      "Size SQM": "198-315",
      "Monthly Rate QAR": 27000,
      "Monthly Rate USD Approx": 7397.26,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "With gym access, Beach access, discount on F&B and Spa",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": null,
      "Contact Email": null,
      "Contact Phone": "+974 66289665",
      "Website URL": "https://www.thetownhouses.qa/",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": "https://georgetown.box.com/s/bi13tlcm9t2o81tgkpsod79kll7dbsyo",
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-004",
      "Approval Status": "Approved",
      "Property Name": "The Town House Hilton The Pearl",
      "Category": "Villa",
      "Area": "The Pearl",
      "Address": "Tower AQ-07, Pearl Boulevard in the Abraj Quartier at The Pearl-Qatar, Doha",
      "Unit Type": "3 Bedroom Villa with Pool",
      "Bedrooms": 3,
      "Size SQM": 220,
      "Monthly Rate QAR": 32000,
      "Monthly Rate USD Approx": 8767.12,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "With gym access, Beach access, discount on F&B and Spa",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": null,
      "Contact Email": null,
      "Contact Phone": "+974 66289665",
      "Website URL": "https://www.thetownhouses.qa/",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": "https://georgetown.box.com/s/dfw9rhp6xnok7gk6feubk7y78w10ciu3",
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-005",
      "Approval Status": "Approved",
      "Property Name": "Grand Hyatt Doha Hotel & Villas.",
      "Category": "Villa",
      "Area": "The Pearl",
      "Address": "Pearl Blvd, Doha, Qatar",
      "Unit Type": "2 Bedroom Ground Floor",
      "Bedrooms": 2,
      "Size SQM": 175,
      "Monthly Rate QAR": 34000,
      "Monthly Rate USD Approx": 9315.07,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Complimentary access to Wi-Fi Internet\nComplimentary access to Gym, Spa and P...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Mariem Limem",
      "Contact Email": "mariem.limem@hyatt.com",
      "Contact Phone": "+974 30170178",
      "Website URL": "https://www.hyatt.com/grand-hyatt/en-US/dohgh-grand-hyatt-doha-hotel-and-villas/rooms/RS2B?",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-006",
      "Approval Status": "Approved",
      "Property Name": "Grand Hyatt Doha Hotel & Villas.",
      "Category": "Villa",
      "Area": "The Pearl",
      "Address": "Pearl Blvd, Doha, Qatar",
      "Unit Type": "3 Bedroom Ground Floor",
      "Bedrooms": 3,
      "Size SQM": 241,
      "Monthly Rate QAR": 38000,
      "Monthly Rate USD Approx": 10410.96,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Complimentary access to Wi-Fi Internet\nComplimentary access to Gym, Spa and P...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Mariem Limem",
      "Contact Email": "mariem.limem@hyatt.com",
      "Contact Phone": "+974 30170178",
      "Website URL": "https://www.hyatt.com/grand-hyatt/en-US/dohgh-grand-hyatt-doha-hotel-and-villas/rooms/RS3B?",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://lh3.googleusercontent.com/p/AF1QipMtnZQA3SKbe2z2m2bHtXrkc3mg1YLNsSY_UPhd=s680-w680-h510-rw",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-007",
      "Approval Status": "Approved",
      "Property Name": "Grand Hyatt Doha Hotel & Villas.",
      "Category": "Villa",
      "Area": "The Pearl",
      "Address": "Pearl Blvd, Doha, Qatar",
      "Unit Type": "4 Bedroom Ground Floor",
      "Bedrooms": 4,
      "Size SQM": 365,
      "Monthly Rate QAR": 65000,
      "Monthly Rate USD Approx": 17808.22,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Complimentary access to Wi-Fi Internet\nComplimentary access to Gym, Spa and P...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Mariem Limem",
      "Contact Email": "mariem.limem@hyatt.com",
      "Contact Phone": "+974 30170178",
      "Website URL": "https://www.hyatt.com/grand-hyatt/en-US/dohgh-grand-hyatt-doha-hotel-and-villas/rooms/RS4V?",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-008",
      "Approval Status": "Approved",
      "Property Name": "Katara Hills Doha, LXR Hotels & Resorts",
      "Category": "Villa",
      "Area": "Katara",
      "Address": "Katara Cultural Village, Doha, Qatar",
      "Unit Type": "3-Bedroom Villa with Pool",
      "Bedrooms": 3,
      "Size SQM": 657,
      "Monthly Rate QAR": 270000,
      "Monthly Rate USD Approx": 73972.6,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "20% Discount on Food & Beverage\n20% Discount on Spa Services\nComplimentary ac...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Ghofrane Touaiti ...",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.hilton.com/en/hotels/dohqkol-katara-hills-doha/",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://assets.hiltonstatic.com/hilton-asset-cache/image/upload/c_fill,w_4498,h_3000,q_90,f_auto/c_fill,w_1920,h_1280,q_90,f_auto/Imagery/Property%20Photography/LXR/D/DOHQKOL/DOHQK_181.jpg",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": "https://georgetown.box.com/s/rbhsygmph5bb4dfq6b3y7haqny4tg9xq",
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-009",
      "Approval Status": "Approved",
      "Property Name": "Katara Hills Doha, LXR Hotels & Resorts",
      "Category": "Villa",
      "Area": "Katara",
      "Address": "Katara Cultural Village, Doha, Qatar",
      "Unit Type": "1-Bedroom Villa with Pool",
      "Bedrooms": 1,
      "Size SQM": 164,
      "Monthly Rate QAR": 120000,
      "Monthly Rate USD Approx": 32876.71,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "20% Discount on Food & Beverage\n20% Discount on Spa Services\nComplimentary ac...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Ghofrane Touaiti ...",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.hilton.com/en/hotels/dohqkol-katara-hills-doha/",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": "https://georgetown.box.com/s/prrqp1px27mgtw389pp3u7dywz72927f",
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-010",
      "Approval Status": "Approved",
      "Property Name": "Maysan Doha, LXR Hotels & Resorts",
      "Category": "Villa",
      "Area": "Aspire / Baaya",
      "Address": "Baaya District, Furousiya St, Doha (near Villagio and Aspire)",
      "Unit Type": "2-Bedroom Villa with Pool",
      "Bedrooms": 2,
      "Size SQM": 230,
      "Monthly Rate QAR": 80000,
      "Monthly Rate USD Approx": 21917.81,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "20% Discount on Food & Beverage\n20% Discount on Spa Services\nComplimentary ac...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Ghofrane Touaiti ...",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.hilton.com/en/hotels/dohpaol-maysan-doha/",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://images.trvl-media.com/lodging/89000000/88110000/88105600/88105548/32854cbe.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": "https://georgetown.box.com/s/tiem5kjkj025mzy3c8s2dd9c0j8ys7sr",
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-011",
      "Approval Status": "Approved",
      "Property Name": "Al Messila, a Luxury Collection Resort & Spa, Doha",
      "Category": "Villa",
      "Area": null,
      "Address": "Zone 36, Street 827, Building 21 (Um Al Saneem Street)",
      "Unit Type": "2 Bedroom Villa",
      "Bedrooms": 2,
      "Size SQM": 183,
      "Monthly Rate QAR": 45000,
      "Monthly Rate USD Approx": 12328.77,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Exclusive bathroom amenity line.\nExclusive bathroom amenity line.\nComplimenta...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "TAWFEQ ISSA",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.marriott.com/en-us/hotels/dohla-al-messila-a-luxury-collection-resort-and-spa-doha/overview/",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://cache.marriott.com/is/image/marriotts7prod/lc-dohla-al-messila-resort--31820:Wide-Hor?wid=1336&fit=constrain",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": "https://georgetown.box.com/s/v23cfe31s49khxefqmvgtv6r28dzyyqz",
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-012",
      "Approval Status": "Approved",
      "Property Name": "Al Messila, a Luxury Collection Resort & Spa, Doha",
      "Category": "Villa",
      "Area": null,
      "Address": "Zone 36, Street 827, Building 21 (Um Al Saneem Street)",
      "Unit Type": "3 Bedroom Villa",
      "Bedrooms": 3,
      "Size SQM": 344,
      "Monthly Rate QAR": 100000,
      "Monthly Rate USD Approx": 27397.26,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Exclusive bathroom amenity line.\nExclusive bathroom amenity line.\nComplimenta...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "TAWFEQ ISSA",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.marriott.com/en-us/hotels/dohla-al-messila-a-luxury-collection-resort-and-spa-doha/overview/",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": "https://georgetown.box.com/s/g6aguqjvwk0fg9dfeldaftlj5yfekrqw",
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-013",
      "Approval Status": "Approved",
      "Property Name": "The Chedi Katara Hotel & Resort",
      "Category": "Villa",
      "Area": "Katara",
      "Address": "Katara Cultural Village، 834 Shakespeare St, Doha, Qatar",
      "Unit Type": "2 Bedroom Villa",
      "Bedrooms": 2,
      "Size SQM": 161,
      "Monthly Rate QAR": 150000,
      "Monthly Rate USD Approx": 41095.89,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Breakfast only or Breakfast & Dinner\n20% off on Food & Beverage\n20% off at ...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Hajar El Magouri",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.ghmhotels.com/en/katara/accommodation/two-bedroom-villa/",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/2c/37/28/facade-pool-reflection.jpg?w=900&h=500&s=1",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-014",
      "Approval Status": "Approved",
      "Property Name": "The Chedi Katara Hotel & Resort",
      "Category": "Villa",
      "Area": "Katara",
      "Address": "Katara Cultural Village، 834 Shakespeare St, Doha, Qatar",
      "Unit Type": "3 Bedroom Villa",
      "Bedrooms": 3,
      "Size SQM": 210,
      "Monthly Rate QAR": 210000,
      "Monthly Rate USD Approx": 57534.25,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Breakfast only or Breakfast & Dinner\n20% off on Food & Beverage\n20% off at ...",
      "Cancellation Policy": "Below rates are non-cancellable and non-refundable except force major conditi...",
      "Contact Name": "Hajar El Magouri",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.ghmhotels.com/en/katara/accommodation/three-bedroom-villa/",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-015",
      "Approval Status": "Approved",
      "Property Name": "City Centre Rotana",
      "Category": "Serviced Apartment",
      "Area": "City Center / Diplomatic Area",
      "Address": "850 Conference Centre, Doha, Qatar",
      "Unit Type": "1 Bedroom Apartment - City View",
      "Bedrooms": 1,
      "Size SQM": 90,
      "Monthly Rate QAR": 13000,
      "Monthly Rate USD Approx": 3561.64,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Outdoor swimming pool\nFree Wifi & Free parking\nFitness center & Spa\n4 restaur...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "Hajar El Magouri",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.rotana.com/rotanahotelandresorts/qatar/doha/citycentrerotanadoha/accommodation/apartments",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/597256601.jpg?k=6f8e0b8c3de14609a6dbda809e31bfd93567118305ac46f3a9c9d7f8d56cb8ff&o=",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-016",
      "Approval Status": "Approved",
      "Property Name": "City Centre Rotana",
      "Category": "Serviced Apartment",
      "Area": "City Center / Diplomatic Area",
      "Address": "850 Conference Centre, Doha, Qatar",
      "Unit Type": "2 Bedroom Apartment - City View",
      "Bedrooms": 2,
      "Size SQM": 131,
      "Monthly Rate QAR": 16000,
      "Monthly Rate USD Approx": 4383.56,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Outdoor swimming pool\nFree Wifi & Free parking\nFitness center & Spa\n4 restaur...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "Hajar El Magouri",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.rotana.com/rotanahotelandresorts/qatar/doha/citycentrerotanadoha/accommodation/apartments",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-017",
      "Approval Status": "Approved",
      "Property Name": "ALEPH DOHA RESIDENCES – CURIO COLLECTION BY HILTON",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Aba Al Hanin Bil Hanin Street, West Bay, Doha, Qatar, PO Box 24767",
      "Unit Type": "1 Bedroom Sky Suite",
      "Bedrooms": 1,
      "Size SQM": "60-71",
      "Monthly Rate QAR": 11000,
      "Monthly Rate USD Approx": 3013.7,
      "Rate Notes": null,
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "Utilities (water, electricity)\nCutlery, crockery and utensils\nParking slot\nWa...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "Hajar El Magouri",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": null,
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://artcwbsv0007-prod.azurewebsites.net/sites/default/files/styles/portfolio_banner/public/2024-06/001_39.jpg.webp?itok=IL9VaYIk",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-018",
      "Approval Status": "Approved",
      "Property Name": "ALEPH DOHA RESIDENCES – CURIO COLLECTION BY HILTON",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Aba Al Hanin Bil Hanin Street, West Bay, Doha, Qatar, PO Box 24767",
      "Unit Type": "2 bedroom Sky apartment – city view",
      "Bedrooms": 2,
      "Size SQM": 127,
      "Monthly Rate QAR": 13000,
      "Monthly Rate USD Approx": 3561.64,
      "Rate Notes": null,
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "Utilities (water, electricity)\nCutlery, crockery and utensils\nParking slot\nWa...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "Hajar El Magouri",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://3d360.appraiser.center/show/?m=m8myfL7LWck&mpu=238",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-019",
      "Approval Status": "Approved",
      "Property Name": "ALEPH DOHA RESIDENCES – CURIO COLLECTION BY HILTON",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Aba Al Hanin Bil Hanin Street, West Bay, Doha, Qatar, PO Box 24767",
      "Unit Type": "2 Deluxe Bedroom +Maid Room",
      "Bedrooms": 2,
      "Size SQM": 127,
      "Monthly Rate QAR": 14000,
      "Monthly Rate USD Approx": 3835.62,
      "Rate Notes": null,
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "Utilities (water, electricity)\nCutlery, crockery and utensils\nParking slot\nWa...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "Hajar El Magouri",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": null,
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-020",
      "Approval Status": "Approved",
      "Property Name": "ALEPH DOHA RESIDENCES – CURIO COLLECTION BY HILTON",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Aba Al Hanin Bil Hanin Street, West Bay, Doha, Qatar, PO Box 24767",
      "Unit Type": "3 bedroom Sky apartment",
      "Bedrooms": 3,
      "Size SQM": 190,
      "Monthly Rate QAR": 19000,
      "Monthly Rate USD Approx": 5205.48,
      "Rate Notes": null,
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "Utilities (water, electricity)\nCutlery, crockery and utensils\nParking slot\nWa...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "Hajar El Magouri",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://3d360.appraiser.center/show/?m=NVCHtqqQQYR&mpu=238",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-021",
      "Approval Status": "Approved",
      "Property Name": "Banyan Tree Doha",
      "Category": "Serviced Apartment",
      "Area": null,
      "Address": "P.O. Box 4928 Al Khaleej St, Doha",
      "Unit Type": "2 Bedroom Apartment ",
      "Bedrooms": 2,
      "Size SQM": "155-260",
      "Monthly Rate QAR": 16000,
      "Monthly Rate USD Approx": 4383.56,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Benefits include:\n• All utilities (water, electricity, A/C)\n• Complimentary W...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": null,
      "Contact Phone": "+974 44103260",
      "Website URL": "https://www.banyantree.com/qatar/doha/residences/two-bedroom-bliss-apartment",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://www.banyantree.com/assets/2021-10/bt-doha-masthead%20%281%29.jpg",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-022",
      "Approval Status": "Approved",
      "Property Name": "Banyan Tree Doha",
      "Category": "Serviced Apartment",
      "Area": null,
      "Address": "P.O. Box 4928 Al Khaleej St, Doha",
      "Unit Type": "3 Bedroom Apartment ",
      "Bedrooms": 3,
      "Size SQM": "225-280",
      "Monthly Rate QAR": 20000,
      "Monthly Rate USD Approx": 5479.45,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Benefits include:\n• All utilities (water, electricity, A/C)\n• Complimentary W...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": null,
      "Contact Phone": "+974 44103260",
      "Website URL": "https://www.banyantree.com/qatar/doha/residences/three-bedroom-bliss-residence",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-023",
      "Approval Status": "Approved",
      "Property Name": "Banyan Tree Doha",
      "Category": "Serviced Apartment",
      "Area": null,
      "Address": "P.O. Box 4928 Al Khaleej St, Doha",
      "Unit Type": "4 Bedroom Apartment",
      "Bedrooms": 4,
      "Size SQM": "290",
      "Monthly Rate QAR": 42000,
      "Monthly Rate USD Approx": 11506.85,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Benefits include:\n• All utilities (water, electricity, A/C)\n• Complimentary W...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": null,
      "Contact Phone": "+974 44103260",
      "Website URL": "https://www.banyantree.com/qatar/doha/residences/four-bedroom-harmony-sky-residence",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-024",
      "Approval Status": "Approved",
      "Property Name": "Delta Hotels City Center Doha",
      "Category": "Serviced Apartment",
      "Area": null,
      "Address": "Umm Arsaan St, Doha, Qatar",
      "Unit Type": "2 Bedroom Apartment, City View ",
      "Bedrooms": 2,
      "Size SQM": "127",
      "Monthly Rate QAR": 13000,
      "Monthly Rate USD Approx": 3561.64,
      "Rate Notes": null,
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "24 h available maintenance team\n24 h available front desk assistance\n24 h ava...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": null,
      "Contact Phone": "+974 44103260",
      "Website URL": "https://www.marriott.com/en-us/hotels/dohdc-delta-hotels-city-center-doha/rooms/#roomPoolCode=topt",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/64/ba/03/dohdc-exterior-shot.jpg?w=900&h=500&s=1",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-025",
      "Approval Status": "Approved",
      "Property Name": "Delta Hotels City Center Doha",
      "Category": "Serviced Apartment",
      "Area": null,
      "Address": "Umm Arsaan St, Doha, Qatar",
      "Unit Type": "3 Bedroom Apartment, City View \n3 Bedroom Apartment, Sea View ",
      "Bedrooms": 3,
      "Size SQM": "171",
      "Monthly Rate QAR": 15000,
      "Monthly Rate USD Approx": 4109.59,
      "Rate Notes": null,
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "24 h available maintenance team\n24 h available front desk assistance\n24 h ava...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": null,
      "Contact Phone": "+974 44103260",
      "Website URL": "https://www.marriott.com/en-us/hotels/dohdc-delta-hotels-city-center-doha/rooms/#roomPoolCode=thbr",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-026",
      "Approval Status": "Approved",
      "Property Name": "HILTON THE PEARL",
      "Category": "Serviced Apartment",
      "Area": "The Pearl",
      "Address": "Tower AQ-07، Abraj Quartier, Pearl Blvd, Doha, Qatar",
      "Unit Type": "1 Bedroom Deluxe Suite with Balcony ",
      "Bedrooms": 1,
      "Size SQM": "99",
      "Monthly Rate QAR": 12000,
      "Monthly Rate USD Approx": 3287.67,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Buffet Breakfast\n•20% Food & Beverage discount in hotel outlets.\n•Wireless in...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": null,
      "Contact Phone": "+974 44103260",
      "Website URL": null,
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://lh3.googleusercontent.com/proxy/wbLvHE8HiNO5tBQ0bSeNnYpNeJYGu4pz9JZR8aan_9t2dSXgCz0hCDbD2GsYvhPdGGkyStz0ehsBTH6sIEUje2aOvJ0yfWyiBmqYKziGsTpRsO0RnzfsqBOXyAc5t1SVJfeUic6b2Nt4V6XAyx-3vp06562x_w=s680-w680-h510-rw",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-027",
      "Approval Status": "Approved",
      "Property Name": "HILTON THE PEARL",
      "Category": "Serviced Apartment",
      "Area": "The Pearl",
      "Address": "Tower AQ-07، Abraj Quartier, Pearl Blvd, Doha, Qatar",
      "Unit Type": "1 Bedroom Suprior Suite with Balcony ",
      "Bedrooms": 1,
      "Size SQM": "99",
      "Monthly Rate QAR": 13250,
      "Monthly Rate USD Approx": 3630.14,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Buffet Breakfast\n•20% Food & Beverage discount in hotel outlets.\n•Wireless in...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": null,
      "Contact Phone": "+974 44103260",
      "Website URL": null,
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-028",
      "Approval Status": "Approved",
      "Property Name": "HILTON THE PEARL",
      "Category": "Serviced Apartment",
      "Area": "The Pearl",
      "Address": "Tower AQ-07، Abraj Quartier, Pearl Blvd, Doha, Qatar",
      "Unit Type": "2 Bedroom Suite with Balcony (Inne...",
      "Bedrooms": 2,
      "Size SQM": 136,
      "Monthly Rate QAR": 15000,
      "Monthly Rate USD Approx": 4109.59,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Buffet Breakfast\n•20% Food & Beverage discount in hotel outlets.\n•Wireless in...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": null,
      "Contact Phone": "+974 44103260",
      "Website URL": "https://www.youtube.com/watch?v=fcjhOAlHBMU&list=PLKbsZ_42T9LdnnkH0mAa7wnEys1T-79dz&index=8",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-029",
      "Approval Status": "Approved",
      "Property Name": "HILTON THE PEARL",
      "Category": "Serviced Apartment",
      "Area": "The Pearl",
      "Address": "Tower AQ-07، Abraj Quartier, Pearl Blvd, Doha, Qatar",
      "Unit Type": "2 Bedroom Deluxe Suite without Balcony ",
      "Bedrooms": 2,
      "Size SQM": "131",
      "Monthly Rate QAR": 14250,
      "Monthly Rate USD Approx": 3904.11,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Buffet Breakfast\n•20% Food & Beverage discount in hotel outlets.\n•Wireless in...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": null,
      "Contact Phone": "+974 44103260",
      "Website URL": "https://www.youtube.com/watch?v=tOCgwKPsnnQ&list=PLKbsZ_42T9LdnnkH0mAa7wnEys1T-79dz&index=5",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-030",
      "Approval Status": "Approved",
      "Property Name": "HILTON THE PEARL",
      "Category": "Serviced Apartment",
      "Area": "The Pearl",
      "Address": "Tower AQ-07، Abraj Quartier, Pearl Blvd, Doha, Qatar",
      "Unit Type": "2 Bedroom Deluxe Suite with Balcony ",
      "Bedrooms": 2,
      "Size SQM": 131,
      "Monthly Rate QAR": 16000,
      "Monthly Rate USD Approx": 4383.56,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Buffet Breakfast\n•20% Food & Beverage discount in hotel outlets.\n•Wireless in...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": null,
      "Contact Phone": "+974 44103260",
      "Website URL": "https://www.youtube.com/watch?v=tOCgwKPsnnQ&list=PLKbsZ_42T9LdnnkH0mAa7wnEys1T-79dz&index=5",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-031",
      "Approval Status": "Approved",
      "Property Name": "HILTON THE PEARL",
      "Category": "Serviced Apartment",
      "Area": "The Pearl",
      "Address": "Tower AQ-07، Abraj Quartier, Pearl Blvd, Doha, Qatar",
      "Unit Type": "2 Bedroom Superior Suite with Balcony ",
      "Bedrooms": 2,
      "Size SQM": 171,
      "Monthly Rate QAR": 19500,
      "Monthly Rate USD Approx": 5342.47,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Buffet Breakfast\n•20% Food & Beverage discount in hotel outlets.\n•Wireless in...",
      "Cancellation Policy": "We require one (1) month notice for cancellation",
      "Contact Name": "SYRINE LASSOUED",
      "Contact Email": null,
      "Contact Phone": "+974 44103260",
      "Website URL": "https://www.youtube.com/watch?v=7MtiTXaW-_w&list=PLKbsZ_42T9LdnnkH0mAa7wnEys1T-79dz&index=11",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-032",
      "Approval Status": "Approved",
      "Property Name": "Marriott Executive Apartments City Center, Doha",
      "Category": "Serviced Apartment",
      "Area": "City Center / Diplomatic Area",
      "Address": "Diplomatic Street Area 61, Street 806, Doha, Qatar",
      "Unit Type": "1 Bedroom Premium: \n(May 2026 until 30 October 2026)",
      "Bedrooms": 1,
      "Size SQM": 75,
      "Monthly Rate QAR": 7000,
      "Monthly Rate USD Approx": 1917.81,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Inclusive of all expenses on utilities and electricity\nInclusive of 5 times p...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": null,
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://images.trvl-media.com/lodging/6000000/5140000/5135600/5135554/41890674.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-033",
      "Approval Status": "Approved",
      "Property Name": "Marriott Executive Apartments City Center, Doha",
      "Category": "Serviced Apartment",
      "Area": "City Center / Diplomatic Area",
      "Address": "Diplomatic Street Area 61, Street 806, Doha, Qatar",
      "Unit Type": "2 Bedrooms Deluxe: \n(May 2026 until 30 October 2026)",
      "Bedrooms": 2,
      "Size SQM": 109,
      "Monthly Rate QAR": 9000,
      "Monthly Rate USD Approx": 2465.75,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Inclusive of all expenses on utilities and electricity\nInclusive of 5 times p...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": null,
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-034",
      "Approval Status": "Approved",
      "Property Name": "Marriott Executive Apartments City Center, Doha",
      "Category": "Serviced Apartment",
      "Area": "City Center / Diplomatic Area",
      "Address": "Diplomatic Street Area 61, Street 806, Doha, Qatar",
      "Unit Type": "3 Bedrooms: \n(May 2026 until 30 October 2026)",
      "Bedrooms": 3,
      "Size SQM": "147-170",
      "Monthly Rate QAR": 13000,
      "Monthly Rate USD Approx": 3561.64,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Inclusive of all expenses on utilities and electricity\nInclusive of 5 times p...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": null,
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-035",
      "Approval Status": "Approved",
      "Property Name": "Le Meridien City Center Doha",
      "Category": "Serviced Apartment",
      "Area": "City Center / Diplomatic Area",
      "Address": "Conference Centre, Doha, Qatar",
      "Unit Type": "1 Bedroom : \n(May 2026 until 30 October 2026)",
      "Bedrooms": 1,
      "Size SQM": "90-106",
      "Monthly Rate QAR": 9000,
      "Monthly Rate USD Approx": 2465.75,
      "Rate Notes": null,
      "Pet Friendly": "YES (small breed)",
      "Amenities / Inclusions": "20% discount in restaurants at Le Meridien, Marriott Marquis and JW Marriott ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.marriott.com/en-us/hotels/dohcl-le-meridien-city-center-doha/rooms/#roomPoolCode=OBVI",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://www.marketing-marriott.com/dohcl/images/img_signup.jpg",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-036",
      "Approval Status": "Approved",
      "Property Name": "Le Meridien City Center Doha",
      "Category": "Serviced Apartment",
      "Area": "City Center / Diplomatic Area",
      "Address": "Conference Centre, Doha, Qatar",
      "Unit Type": "2 Bedrooms : (May 2026 until 30 October 2026)",
      "Bedrooms": 2,
      "Size SQM": "120-148",
      "Monthly Rate QAR": 11500,
      "Monthly Rate USD Approx": 3150.68,
      "Rate Notes": null,
      "Pet Friendly": "YES (small breed)",
      "Amenities / Inclusions": "20% discount in restaurants at Le Meridien, Marriott Marquis and JW Marriott ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "http://marriott.com/en-us/hotels/dohcl-le-meridien-city-center-doha/rooms/#roomPoolCode=TBOV",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-037",
      "Approval Status": "Approved",
      "Property Name": "Le Meridien City Center Doha",
      "Category": "Serviced Apartment",
      "Area": "City Center / Diplomatic Area",
      "Address": "Conference Centre, Doha, Qatar",
      "Unit Type": "3 Bedrooms: \n(May 2026 until 30 October 2026)",
      "Bedrooms": 3,
      "Size SQM": 175,
      "Monthly Rate QAR": 15500,
      "Monthly Rate USD Approx": 4246.58,
      "Rate Notes": null,
      "Pet Friendly": "YES (small breed)",
      "Amenities / Inclusions": "20% discount in restaurants at Le Meridien, Marriott Marquis and JW Marriott ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.marriott.com/en-us/hotels/dohcl-le-meridien-city-center-doha/rooms/#roomPoolCode=THVI",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-038",
      "Approval Status": "Approved",
      "Property Name": "MARRIOTT MARQUIS CITY CENTER DOHA HOTEL",
      "Category": "Serviced Apartment",
      "Area": null,
      "Address": "Omar Al Mukhtar Street, Area 61, Street #850, Doha, Qatar",
      "Unit Type": "1 Bedroom ",
      "Bedrooms": 1,
      "Size SQM": "60-106",
      "Monthly Rate QAR": 9500,
      "Monthly Rate USD Approx": 2602.74,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "20% discount in restaurants at Le Meridien, Marriott Marquis and JW Marriott ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.marriott.com/en-us/hotels/dohmq-marriott-marquis-city-center-doha-hotel/rooms/#roomPoolCode=OBAP",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://cache.marriott.com/content/dam/marriott-renditions/DOHMQ/dohmq-exterior-0084-hor-clsc.jpg?output-quality=70&interpolation=progressive-bilinear&downsize=1300px:*",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-039",
      "Approval Status": "Approved",
      "Property Name": "MARRIOTT MARQUIS CITY CENTER DOHA HOTEL",
      "Category": "Serviced Apartment",
      "Area": null,
      "Address": "Omar Al Mukhtar Street, Area 61, Street #850, Doha, Qatar",
      "Unit Type": "2 Bedrooms ",
      "Bedrooms": 2,
      "Size SQM": "100-150",
      "Monthly Rate QAR": 11500,
      "Monthly Rate USD Approx": 3150.68,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "20% discount in restaurants at Le Meridien, Marriott Marquis and JW Marriott ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": null,
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-040",
      "Approval Status": "Approved",
      "Property Name": "MARRIOTT MARQUIS CITY CENTER DOHA HOTEL",
      "Category": "Serviced Apartment",
      "Area": null,
      "Address": "Omar Al Mukhtar Street, Area 61, Street #850, Doha, Qatar",
      "Unit Type": "3 Bedrooms",
      "Bedrooms": 3,
      "Size SQM": 190,
      "Monthly Rate QAR": 15500,
      "Monthly Rate USD Approx": 4246.58,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "20% discount in restaurants at Le Meridien, Marriott Marquis and JW Marriott ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Bernadette M. Castro",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": null,
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-041",
      "Approval Status": "Approved",
      "Property Name": "Marriott Executive Apartments Doha Le Mirage City Walk",
      "Category": "Serviced Apartment",
      "Area": "Msheireb / Bin Mahmoud",
      "Address": "Ibn Mahmoud Street, Bin Mahmoud / Musherib district/near Bin Mahmoud Metro St...",
      "Unit Type": "1 Bedroom-HK (May 2026 until 30 Aug 2026)",
      "Bedrooms": 1,
      "Size SQM": 85,
      "Monthly Rate QAR": 9000,
      "Monthly Rate USD Approx": 2465.75,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "• Fully furnished apartments with air-conditioning, 55” Smart TV, Wi-Fi, in-r...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://my.matterport.com/show/?m=PxcvABJxP9w&cloudEdit=1",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://www.almosafer.com/image/hotels?url=http%3A%2F%2Fhotelcms-contents-live.almosafer.com%2Fca133138-ce2f-4cb1-9b5b-78f41da370a3.jpg&w=3840&q=75",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-042",
      "Approval Status": "Approved",
      "Property Name": "Marriott Executive Apartments Doha Le Mirage City Walk",
      "Category": "Serviced Apartment",
      "Area": "Msheireb / Bin Mahmoud",
      "Address": "Ibn Mahmoud Street, Bin Mahmoud / Musherib district/near Bin Mahmoud Metro St...",
      "Unit Type": "2 Bedrooms-HK",
      "Bedrooms": 2,
      "Size SQM": "118-157",
      "Monthly Rate QAR": 11500,
      "Monthly Rate USD Approx": 3150.68,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "• Fully furnished apartments with air-conditioning, 55” Smart TV, Wi-Fi, in-r...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://my.matterport.com/show/?m=ZdTgZbq1VLi&cloudEdit=1",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-043",
      "Approval Status": "Approved",
      "Property Name": "Marriott Executive Apartments Doha Le Mirage City Walk",
      "Category": "Serviced Apartment",
      "Area": "Msheireb / Bin Mahmoud",
      "Address": "Ibn Mahmoud Street, Bin Mahmoud / Musherib district/near Bin Mahmoud Metro St...",
      "Unit Type": "2 Bedrooms-HK Duplex",
      "Bedrooms": 2,
      "Size SQM": 157,
      "Monthly Rate QAR": null,
      "Monthly Rate USD Approx": null,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "• Fully furnished apartments with air-conditioning, 55” Smart TV, Wi-Fi, in-r...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://my.matterport.com/show/?m=7ppFdd63DR7&cloudEdit=1",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-044",
      "Approval Status": "Approved",
      "Property Name": "Le Mirage Downtown:",
      "Category": "Serviced Apartment",
      "Area": "Ras Abu Abboud",
      "Address": "Building 30| Street 210, Ras Abu Abboud Street| Zone 16",
      "Unit Type": "1 Bedroom",
      "Bedrooms": 1,
      "Size SQM": 90,
      "Monthly Rate QAR": 9000,
      "Monthly Rate USD Approx": 2465.75,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "• Free cleaning once per week.\n• Fully equipped kitchen included.\n• Includes ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://my.matterport.com/show/?m=uF3F2j6NfJt&cloudEdit=1",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://images.trvl-media.com/lodging/95000000/94790000/94787400/94787321/e96b1176.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-045",
      "Approval Status": "Approved",
      "Property Name": "Le Mirage Downtown:",
      "Category": "Serviced Apartment",
      "Area": "Ras Abu Abboud",
      "Address": "Building 30| Street 210, Ras Abu Abboud Street| Zone 16",
      "Unit Type": "2 Bedrooms (May 2026 until 31 Aug 2026)",
      "Bedrooms": 2,
      "Size SQM": 126,
      "Monthly Rate QAR": 11500,
      "Monthly Rate USD Approx": 3150.68,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "• Free cleaning once per week.\n• Fully equipped kitchen included.\n• Includes ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://my.matterport.com/show/?m=LSnUBMwfNbm&cloudEdit=1",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-047",
      "Approval Status": "Approved",
      "Property Name": "Baraha Town",
      "Category": "Serviced Apartment",
      "Area": "Mesaimeer",
      "Address": "6FRR+XJQ, Mesaimeer Rd, Doha, Qatar",
      "Unit Type": "1 Bedroom-HK ",
      "Bedrooms": 1,
      "Size SQM": "91",
      "Monthly Rate QAR": 6500,
      "Monthly Rate USD Approx": 1780.82,
      "Rate Notes": null,
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "• Free cleaning once per week.\n• Fully equipped kitchen included.\n• Includes ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://my.matterport.com/show/?m=SVho2Bhz8Y1&cloudEdit=1",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://www.lemiragefitout.com/wp-content/uploads/2022/06/baraha-town2.jpg",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-048",
      "Approval Status": "Approved",
      "Property Name": "Le Mirage Icon",
      "Category": "Serviced Apartment",
      "Area": null,
      "Address": "Nasr Bin Sayyar Street ,7GH7+9QX, Doha, Qatar",
      "Unit Type": "2 Bedroom-Hk ",
      "Bedrooms": 2,
      "Size SQM": "146",
      "Monthly Rate QAR": 10500,
      "Monthly Rate USD Approx": 2876.71,
      "Rate Notes": null,
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "• Free cleaning once per week.\n• Fully equipped kitchen included.\n• Includes ...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://my.matterport.com/show/?m=SVho2Bhz8Y1&cloudEdit=1",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://d2kihw5e8drjh5.cloudfront.net/eyJidWNrZXQiOiJ1dGEtaW1hZ2VzIiwia2V5IjoicGxhY2VfaW1nLzJFVHNYUDZUU295dVdTTmR4U3h6Q0EiLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjY0MCwiaGVpZ2h0Ijo2NDAsImZpdCI6Imluc2lkZSJ9LCJyb3RhdGUiOm51bGwsInRvRm9ybWF0IjogIndlYnAifX0=",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-049",
      "Approval Status": "Approved",
      "Property Name": "InterContinental Doha The City",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Doha West Bay /Near DECC Metro",
      "Unit Type": "1 Bedroom – residence suite ",
      "Bedrooms": 1,
      "Size SQM": "100-124",
      "Monthly Rate QAR": 11000,
      "Monthly Rate USD Approx": 3013.7,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Benefits:\nFully covered water and electricity bills\nComplimentary WiFi\n20% discount on food and beverage,\n50% discount on laundry\nHousekeeping services twice per week (one deep and one light cleaning)\nUnderground parking area with a valet service\nAccess to open air swimming pool on level 46th\nMembership at the fitness center on floor 46 with discounts for a variety of classes\n",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://goenvoi.com/360-virtual-tours-doha-qatar/intercontinental-doha-the-city/One-Bedroom-Residence-Suite/",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://digital.ihg.com/is/image/ihg/intercontinental-doha-4094399166-original",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-050",
      "Approval Status": "Approved",
      "Property Name": "InterContinental Doha The City",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Doha West Bay /Near DECC Metro",
      "Unit Type": "2 Bedroom – residence suite ",
      "Bedrooms": 2,
      "Size SQM": "127-147",
      "Monthly Rate QAR": 14500,
      "Monthly Rate USD Approx": 3972.6,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Benefits:\nFully covered water and electricity bills\nComplimentary WiFi\n20% di...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://goenvoi.com/360-virtual-tours-doha-qatar/intercontinental-doha-the-city/2-Bedroom-Residence-Suite-03-type/",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-051",
      "Approval Status": "Approved",
      "Property Name": "InterContinental Doha The City",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Doha West Bay /Near DECC Metro",
      "Unit Type": "3 Bedroom – residence suite ",
      "Bedrooms": 3,
      "Size SQM": "146-185",
      "Monthly Rate QAR": 16500,
      "Monthly Rate USD Approx": 4520.55,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Benefits:\nFully covered water and electricity bills\nComplimentary WiFi\n20% di...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://goenvoi.com/360-virtual-tours-doha-qatar/intercontinental-doha-the-city/3-Bedroom-Residence-Suite-08-type/",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-052",
      "Approval Status": "Approved",
      "Property Name": "Wyndham Doha West Bay (next to Gate Mall)",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Maysaloun Street, West Bay | P.O. Box 5649 | Doha | Qatar",
      "Unit Type": " 1 Bedroom Standard Apartment ",
      "Bedrooms": 1,
      "Size SQM": "65",
      "Monthly Rate QAR": 10000,
      "Monthly Rate USD Approx": 2739.73,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "Complimentary high-speed Wi-Fi\nRestaurant discounts: 20% at selected restaurants and Lemon Garden, 25% at Pinna Bakery & Café, 20% at Tche Tche, and 15% at Sandwich Factory\nDiscounts on laundry, beauty salon, F45 memberships, and FS Pilates packages\nFree cleaning service twice a week\nComplimentary access to gym, steam, sauna, indoor/outdoor pool, and Kid’s Box\nUtilities included (electricity and water)\nTwo free parking spaces\nSatellite TV channels included\n24/7 front desk, concierge, housekeeping, maintenance, and security services",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.youtube.com/watch?v=8QyUI4Wf59c",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://ik.imgkit.net/3vlqs5axxjf/external/https://media.iceportal.com/109548/photos/74662850_XL.jpg?tr=w-1200%2Cfo-auto",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-053",
      "Approval Status": "Approved",
      "Property Name": "Wyndham Doha West Bay (next to Gate Mall)",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Maysaloun Street, West Bay | P.O. Box 5649 | Doha | Qatar",
      "Unit Type": "1 Bedroom Premuim  Apartment ",
      "Bedrooms": 1,
      "Size SQM": "86",
      "Monthly Rate QAR": 11000,
      "Monthly Rate USD Approx": 3013.7,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "• Complimentary High-Speed Wi-Fi Internet.\n• 20% discount in se...",
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.youtube.com/watch?v=ZHYzJMKd_Bo",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-054",
      "Approval Status": "Approved",
      "Property Name": "Wyndham Doha West Bay (next to Gate Mall)",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Maysaloun Street, West Bay | P.O. Box 5649 | Doha | Qatar",
      "Unit Type": "2 Bedroom Standard Apartment Standard ",
      "Bedrooms": 2,
      "Size SQM": "105",
      "Monthly Rate QAR": 13000,
      "Monthly Rate USD Approx": 3561.64,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": null,
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.youtube.com/watch?v=eJMhe8zr9j0",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-055",
      "Approval Status": "Approved",
      "Property Name": "Wyndham Doha West Bay (next to Gate Mall)",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Maysaloun Street, West Bay | P.O. Box 5649 | Doha | Qatar",
      "Unit Type": "2 Bedroom Premuim Standard Apartment",
      "Bedrooms": 2,
      "Size SQM": "146",
      "Monthly Rate QAR": 14000,
      "Monthly Rate USD Approx": 3835.62,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": null,
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.youtube.com/watch?v=fNjct41mpNg",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-056",
      "Approval Status": "Approved",
      "Property Name": "Wyndham Doha West Bay (next to Gate Mall)",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Maysaloun Street, West Bay | P.O. Box 5649 | Doha | Qatar",
      "Unit Type": "3 Bedroom Apartment ",
      "Bedrooms": 3,
      "Size SQM": "173",
      "Monthly Rate QAR": 16000,
      "Monthly Rate USD Approx": 4383.56,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": null,
      "Cancellation Policy": "Leaving the country : Should the guest leave the country we require two (2) m...",
      "Contact Name": "Shafqat Rasool, Sales and Marketing Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://www.youtube.com/watch?v=p58zKnT5CJ0",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-057",
      "Approval Status": "Approved",
      "Property Name": "Retaj Hotels & Hospitality - Retaj Baywalk Residence",
      "Category": "Serviced Apartment",
      "Area": "The Pearl",
      "Address": "( VIVA Bhariya 8 ) Retaj Baywalk Residence The  Pearl, Street 140, Zone 66, T...",
      "Unit Type": "1 Bedroom Standard ",
      "Bedrooms": 1,
      "Size SQM": "77",
      "Monthly Rate QAR": 9500,
      "Monthly Rate USD Approx": 2602.74,
      "Rate Notes": null,
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "Retaj Baywalk Residence provides residents all the amenities, utilities and support\nwithin easy reach.\n• 303+ private parking spaces\n• Gym\n• Spa & Moroccan Bath\n• Mokarabia Coffee shop &\nBBQ Areas\n• Kids Play Areas\n• Swimming Pool, Kids Pool,\nJacuzzi & access to the beach\n• Lobby Lounge",
      "Cancellation Policy": "We require one (1) month notice for cancellation **Prices may vary on the un...",
      "Contact Name": "Farah Aissou",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://retaj-baywalk-residence.com/?mphb_room_type=one-bedroom-apartments",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/32/72/56/0a/caption.jpg?w=900&h=500&s=1",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": "2026-05-20",
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-058",
      "Approval Status": "Approved",
      "Property Name": "The Bentley Luxury Hotel & Suites & Thirty Five Luxury Apartments",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Al Sham Street 870, Building 41, Zone 63, Westbay",
      "Unit Type": "1 Bedroom Apartment",
      "Bedrooms": 1,
      "Size SQM": null,
      "Monthly Rate QAR": 8000,
      "Monthly Rate USD Approx": 2191.78,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "WiFi\nKahramaa (utilities)\nAccess to rooftop swimming pool\nGym access",
      "Cancellation Policy": null,
      "Contact Name": "Ahmad Saad, Cluster Senior Sales Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://thebentleytower.com/",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://lh3.googleusercontent.com/p/AF1QipMqV7CxGMyr1EGtUMcRGTwmTfejtQAH77zf0jzn=s680-w680-h510-rw",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": null,
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-059",
      "Approval Status": "Approved",
      "Property Name": "The Bentley Luxury Hotel & Suites & Thirty Five Luxury Apartments",
      "Category": "Serviced Apartment",
      "Area": "West Bay",
      "Address": "Al Sham Street 870, Building 41, Zone 63, Westbay",
      "Unit Type": "2 Bedroom Apartment",
      "Bedrooms": 2,
      "Size SQM": null,
      "Monthly Rate QAR": 10500,
      "Monthly Rate USD Approx": 2876.712329,
      "Rate Notes": null,
      "Pet Friendly": "NO",
      "Amenities / Inclusions": "WiFi\nKahramaa (utilities)\nAccess to rooftop swimming pool\nGym access",
      "Cancellation Policy": null,
      "Contact Name": "Ahmad Saad, Cluster Senior Sales Manager",
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": "https://thebentleytower.com/",
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": "https://lh3.googleusercontent.com/p/AF1QipMqV7CxGMyr1EGtUMcRGTwmTfejtQAH77zf0jzn=s680-w680-h510-rw",
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": null,
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-060",
      "Approval Status": null,
      "Property Name": "Swissotel Corniche Park Towers Doha",
      "Category": "Serviced Apartment",
      "Area": "Corniche",
      "Address": "Corniche, Doha, Qatar",
      "Unit Type": "1 Bedroom Apartment with kitchenette",
      "Bedrooms": 1,
      "Size SQM": null,
      "Monthly Rate QAR": 11000,
      "Monthly Rate USD Approx": 3013.69863,
      "Rate Notes": null,
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "omplimentary access to the pool and recreation facilities.\n• Complimentary access to The Spa, excluding treatments.\n• Complimentary mineral water in the room daily.\n• Complimentary Wi-Fi in all public areas and guest rooms.\n• Satellite TV.\n• 24/7 In Room Dining Service",
      "Cancellation Policy": null,
      "Contact Name": null,
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": null,
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": null,
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-061",
      "Approval Status": null,
      "Property Name": "Swissotel Corniche Park Towers Doha",
      "Category": "Serviced Apartment",
      "Area": "Corniche",
      "Address": "Corniche, Doha, Qatar",
      "Unit Type": "1 Bedroom Apartment with kitchenette",
      "Bedrooms": 1,
      "Size SQM": null,
      "Monthly Rate QAR": 13750,
      "Monthly Rate USD Approx": 3767.123288,
      "Rate Notes": null,
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "omplimentary access to the pool and recreation facilities.\n• Complimentary access to The Spa, excluding treatments.\n• Complimentary mineral water in the room daily.\n• Complimentary Wi-Fi in all public areas and guest rooms.\n• Satellite TV.\n• 24/7 In Room Dining Service",
      "Cancellation Policy": null,
      "Contact Name": null,
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": null,
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": null,
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-062",
      "Approval Status": null,
      "Property Name": "Swissotel Corniche Park Towers Doha",
      "Category": "Serviced Apartment",
      "Area": "Corniche",
      "Address": "Corniche, Doha, Qatar",
      "Unit Type": "2 Bedroom Apartment with kitchenette",
      "Bedrooms": 2,
      "Size SQM": null,
      "Monthly Rate QAR": 16000,
      "Monthly Rate USD Approx": 4383.561644,
      "Rate Notes": null,
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "omplimentary access to the pool and recreation facilities.\n• Complimentary access to The Spa, excluding treatments.\n• Complimentary mineral water in the room daily.\n• Complimentary Wi-Fi in all public areas and guest rooms.\n• Satellite TV.\n• 24/7 In Room Dining Service",
      "Cancellation Policy": null,
      "Contact Name": null,
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": null,
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": null,
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-063",
      "Approval Status": null,
      "Property Name": "Swissotel Corniche Park Towers Doha",
      "Category": "Serviced Apartment",
      "Area": "Corniche",
      "Address": "Corniche, Doha, Qatar",
      "Unit Type": "2 Bedroom Apartment with kitchen  ( city view) ",
      "Bedrooms": 2,
      "Size SQM": null,
      "Monthly Rate QAR": 16500,
      "Monthly Rate USD Approx": 4520.547945,
      "Rate Notes": null,
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "omplimentary access to the pool and recreation facilities.\n• Complimentary access to The Spa, excluding treatments.\n• Complimentary mineral water in the room daily.\n• Complimentary Wi-Fi in all public areas and guest rooms.\n• Satellite TV.\n• 24/7 In Room Dining Service",
      "Cancellation Policy": null,
      "Contact Name": null,
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": null,
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": null,
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    },
    {
      "Record ID": "CAT-064",
      "Approval Status": null,
      "Property Name": "Swissotel Corniche Park Towers Doha",
      "Category": "Serviced Apartment",
      "Area": "Corniche",
      "Address": "Corniche, Doha, Qatar",
      "Unit Type": "2 Bedroom Apartment with kitchen ( Sea view) ",
      "Bedrooms": 2,
      "Size SQM": null,
      "Monthly Rate QAR": 17000,
      "Monthly Rate USD Approx": 4657.534247,
      "Rate Notes": null,
      "Pet Friendly": "YES",
      "Amenities / Inclusions": "omplimentary access to the pool and recreation facilities.\n• Complimentary access to The Spa, excluding treatments.\n• Complimentary mineral water in the room daily.\n• Complimentary Wi-Fi in all public areas and guest rooms.\n• Satellite TV.\n• 24/7 In Room Dining Service",
      "Cancellation Policy": null,
      "Contact Name": null,
      "Contact Email": null,
      "Contact Phone": null,
      "Website URL": null,
      "Virtual Tour URL": null,
      "Flyer URL": null,
      "Image URL": null,
      "Gallery URLs": null,
      "Booking / Display Notes": null,
      "Internal Notes": null,
      "Last Updated": null,
      "Unit Detail URL": null,
      "Unit Video URL": null,
      "Unit Image URL": null,
      "Unit Display Order": null
    }
  ]
};
